# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{moxie_forum}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Keith Schacht"]
  s.date = %q{2010-09-11}
  s.email = %q{krschacht@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/moxie/admin/forums_controller.rb",
     "app/controllers/moxie/admin_controller.rb",
     "app/controllers/moxie/forums_controller.rb",
     "app/controllers/moxie/posts_controller.rb",
     "app/controllers/moxie/topics_controller.rb",
     "app/helpers/moxie/application_helper.rb",
     "app/helpers/moxie/forums_helper.rb",
     "app/models/moxie/forum.rb",
     "app/models/moxie/post.rb",
     "app/models/moxie/topic.rb",
     "app/views/layouts/forums.html.erb",
     "app/views/moxie/admin/forums/_form.html.erb",
     "app/views/moxie/admin/forums/edit.html.erb",
     "app/views/moxie/admin/forums/index.html.erb",
     "app/views/moxie/admin/forums/new.html.erb",
     "app/views/moxie/admin/forums/show.html.erb",
     "app/views/moxie/admin/index.html.erb",
     "app/views/moxie/forums/authorization_error.html.erb",
     "app/views/moxie/forums/index.html.erb",
     "app/views/moxie/forums/show.html.erb",
     "app/views/moxie/posts/_form.html.erb",
     "app/views/moxie/posts/_post.html.erb",
     "app/views/moxie/topics/_form.html.erb",
     "app/views/moxie/topics/new.html.erb",
     "app/views/moxie/topics/show.html.erb",
     "config/routes.rb",
     "lib/application_helper.rb",
     "lib/moxie_forum.rb",
     "lib/moxie_forum/acts_as_moxie_user/base.rb",
     "lib/moxie_forum/engine.rb",
     "lib/rails/generators/moxie_forum/moxie_forum_generator.rb",
     "lib/rails/generators/moxie_forum/templates/config.yml",
     "lib/rails/generators/moxie_forum/templates/initializer.rb",
     "lib/rails/generators/moxie_forum/templates/migration.rb",
     "lib/rails/generators/moxie_forum/templates/schema.rb",
     "lib/rails/railties/tasks.rake",
     "lib/tasks/tasks.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fantastic forum software for Rails 3}
  s.test_files = [
    "test/generators/moxie_forum_generator_test.rb",
     "test/test_helper.rb",
     "test/unit/forum_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

